### PR TITLE
workaround for an occasional error we see in the ALMA environment

### PR DESCRIPTION
**Pull request by amanningeso**
I can't reliably reproduce this, neither in test cases nor in manual testing. I _think_ it sometimes occurs after an ALMA mirroring error.

### CODE REVIEW

**Comment by amanningeso** [comment]
Hi Rodrigo, what about this one. Is this also solved with your janitor thread startup modifications?

**Comment by rtobar** [comment]
> Hi Rodrigo, what about this one. Is this also solved with your janitor thread startup modifications?

Hi Alisdair, I'm not sure to be honest. I wanted to reason about what could cause the `None` to appear before doing anything, but after dedicating a bit of time this morning I couldn't reach any conclusions. I'd like more time, and I believe this isn't that urgent -- failure in one janitor plug-in doesn't prevent the others from running, even the failing one might work the next time around, and since you're using the null requests store there's nothing to worry about.

Hopefully with some more time I can crack this. If you see any new occurrences could you post here the logs/errors? Thanks!

**Comment by amanningeso** [comment]
Could we approach this the other way around? To merge the small fix now and then investigate? I'll put in a WARN message so that we can easily see if it occurs at all in production.

I did see this happen during testing while I was abusing the ALMA mirroring, despite using the null request store. I think it could have happened as a result of timeouts in the mirroring thread (which have been fixed). Regardless, I would rather have an unnecessary test, and an absolutely overly-paranoid, bomb-proof production deployment.

**Comment by rtobar** [comment]
@amanningeso I've merged the changes as requested.

What I'm not so sure about the fix is that it addresses the failure in one of the janitor plug-ins, but the error isn't plug-in specific, but something that is wrong with the IPC protocol logic between the server and the janitor process (I suspect it doesn't have to do with anything ALMA-mirroring-specific). In other words, even though it was caught in the first janitor plug-in that does a request/reply to/from the server, there could have been a chance that it happened with others. Anyhow, the fix is merged. It could well be that the startup sequence re-ordering commit I pushed last week makes this error even more rare.

**Pull request merged**
